#!/usr/bin/env python3
import json
import os
import subprocess
import concurrent.futures

SECRETS_FILE = os.environ.get("OPENCLAW_SECRETS_JSON", os.path.expanduser("~/workspace/.secrets/secrets_flat.json"))
NODES = ["02", "03", "05"]
LOCAL_ENV = os.path.expanduser("~/.openclaw_env")

def sync_node(node):
    try:
        # 1. SCP the file to a tmp location (Timeout protected + BatchMode to Fail-Fast on auth issues)
        subprocess.run(
            ["scp", "-o", "ConnectTimeout=5", "-o", "BatchMode=yes", "/tmp/.openclaw_env_edge", f"{node}:/tmp/.openclaw_env_incoming"], 
            check=True, stderr=subprocess.DEVNULL, timeout=10
        )
        
        # 2. Remote Injection (Merge incoming secrets while preserving local OpenClaw framework vars)
        if node != "05":
            inject_cmd = (
                # Safely merge incoming vault keys into the edge env while preserving OPENCLAW_ variables
                "touch ~/.openclaw_env && "
                "grep '^export OPENCLAW_' ~/.openclaw_env > /tmp/.openclaw_env_preserved || true && "
                "cat /tmp/.openclaw_env_incoming > ~/.openclaw_env && "
                "cat /tmp/.openclaw_env_preserved >> ~/.openclaw_env && "
                "rm -f /tmp/.openclaw_env_incoming /tmp/.openclaw_env_preserved && "
                "chmod 600 ~/.openclaw_env && "
                "for rc in ~/.zshrc ~/.bashrc ~/.bash_profile; do "
                "  if [ -f \"$rc\" ] && ! grep -q 'source ~/.openclaw_env' \"$rc\"; then "
                "    echo '\\n# OpenClaw Secure Envelope\\n[ -f ~/.openclaw_env ] && source ~/.openclaw_env' >> \"$rc\"; "
                "  fi; "
                "done; "
                "mkdir -p ~/.openclaw_secrets && cp -f ~/.openclaw_env ~/.openclaw_secrets/.env 2>/dev/null || true; "
                "if [ -d ~/openclaw ]; then ln -sf ~/.openclaw_secrets/.env ~/openclaw/.env; fi; "
                "if [ -d ~/workspace/projects/openclaw ]; then ln -sf ~/.openclaw_secrets/.env ~/workspace/projects/openclaw/.env; fi; "
                "if [ -d ~/openclaw ]; then ln -sf ~/.openclaw_secrets/.env ~/openclaw/.env; fi"
            )
            subprocess.run(
                ["ssh", "-o", "ConnectTimeout=5", "-o", "BatchMode=yes", node, inject_cmd], 
                check=True, stderr=subprocess.DEVNULL, timeout=10
            )
            
        return f"✅ Node {node} securely fortified."
    except subprocess.TimeoutExpired:
        return f"❌ Node {node} Failed Fast: TimeoutExpired (Took > 10s)."
    except subprocess.CalledProcessError:
        return f"❌ Node {node} Failed Fast: BatchMode Auth Rejection or Connectivity."
    except Exception as e:
        return f"❌ Node {node} Failed Fast: {type(e).__name__}."

def sync():
    print("🚀 Initiating Vault-to-Env Secure Sync (Concurrent Fail-Fast Mode)...")
    if not os.path.exists(SECRETS_FILE):
        print(f"Error: Flattened secrets file {SECRETS_FILE} not found. Please run flatten_secrets.py first.")
        return

    with open(SECRETS_FILE, "r", encoding="utf-8") as f:
        secrets = json.load(f)

    env_content_local = "# OpenClaw Autogenerated Secure Env (Node 01 Master Vault)\n"
    env_content_edge = "# OpenClaw Autogenerated Secure Env (Edge Node Limited Payload)\n"
    
    # Static Injection of Non-Secret Metadata (Emails, etc.)
    static_metadata = (
        'export EMAIL_126_USER="lxh5147@126.com"\n'
        'export ACADEMIC_EMAIL_USER="xiaohualiu@jhun.edu.cn"\n'
    )
    env_content_local += static_metadata
    env_content_edge += static_metadata
    
    # 🛡️ Boss Directive (Least Privilege): Strictly limit what goes to edge nodes.
    # No private VPN/Mail/SSH/DB passwords should ever leave Node 01.
    edge_allowed_prefixes = (
        "FEISHU_", "GEMINI_", "GOOGLE_", "GROQ_", "OPENAI_", "WANDB_", "HF_", "TAVILY_",
        "GITHUB_", "KAGGLE_", "NVIDIA_", "EXA_", "EMAIL_", "PERSONAL_", "GMAIL_", "ACADEMIC_"
    )

    for k, v in secrets.items():
        v_escaped = str(v).replace('"', '\\"')
        export_line = f'export {k}="{v_escaped}"\n'
        env_content_local += export_line
        
        if k.startswith(edge_allowed_prefixes):
            env_content_edge += export_line

    # 0.5 Preserve local OpenClaw framework vars on Node 01
    if os.path.exists(LOCAL_ENV):
        with open(LOCAL_ENV, "r", encoding="utf-8") as f:
            for line in f:
                if line.startswith("export OPENCLAW_"):
                    env_content_local += line

    # 1. Write locally to Node 01 (Full Privileges)
    with open(LOCAL_ENV, "w", encoding="utf-8") as f:
        f.write(env_content_local)
    os.chmod(LOCAL_ENV, 0o600)
    print(f"✅ Local {LOCAL_ENV} created/updated (chmod 600).")

    # 1.5 Write temporary Edge payload (Limited Privileges)
    edge_env_tmp = "/tmp/.openclaw_env_edge"
    with open(edge_env_tmp, "w", encoding="utf-8") as f:
        f.write(env_content_edge)
        # Fix: Statically inject SKIP_BUILD to avoid 0% CPU lock on Node 02/Edge gateways
        f.write("export OPENCLAW_SKIP_BUILD=1\n")
    os.chmod(edge_env_tmp, 0o600)

    # 2. Inject into local Node 01 bash/zsh profiles
    for rc in [".zshrc", ".bash_profile", ".bashrc"]:
        rc_path = os.path.expanduser(f"~/{rc}")
        if os.path.exists(rc_path):
            with open(rc_path, "r") as f:
                content = f.read()
            if "source ~/.openclaw_env" not in content:
                with open(rc_path, "a") as f:
                    f.write("\n# OpenClaw Secure Secrets Envelope\n[ -f ~/.openclaw_env ] && source ~/.openclaw_env\n")

    print(f"\n⏳ Dispatching concurrent fleet synchronization to {NODES}...")
    # 3. Target remote nodes concurrently with Fail-Fast pool
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
        futures = {executor.submit(sync_node, node): node for node in NODES}
        for future in concurrent.futures.as_completed(futures):
            print("   " + future.result())

    print("\n🎉 Vault-to-Env deployment complete.")

if __name__ == "__main__":
    sync()
