#!/usr/bin/env python3
import json
import os
import subprocess
import concurrent.futures

SECRETS_FILE = os.environ.get("OPENCLAW_SECRETS_JSON", os.path.expanduser("~/workspace/.secrets/secrets_flat.json"))
NODES = ["02", "03", "05"]
LOCAL_ENV = os.path.expanduser("~/.openclaw_env")

def sync_node(node):
    try:
        # 1. SCP the file (Timeout protected + BatchMode to Fail-Fast on auth issues)
        subprocess.run(
            ["scp", "-o", "ConnectTimeout=5", "-o", "BatchMode=yes", LOCAL_ENV, f"{node}:~/.openclaw_env"], 
            check=True, stderr=subprocess.DEVNULL, timeout=10
        )
        
        # 2. Remote Injection (Explicitly skip Windows Node 05 to prevent heterogeneous bash loop hang)
        if node != "05":
            inject_cmd = (
                "chmod 600 ~/.openclaw_env && "
                "for rc in ~/.zshrc ~/.bashrc ~/.bash_profile; do "
                "  if [ -f \"$rc\" ] && ! grep -q 'source ~/.openclaw_env' \"$rc\"; then "
                "    echo '\\n# OpenClaw Secure Envelope\\n[ -f ~/.openclaw_env ] && source ~/.openclaw_env' >> \"$rc\"; "
                "  fi; "
                "done; "
                "mkdir -p ~/.openclaw_secrets && cp -f ~/.openclaw_env ~/.openclaw_secrets/.env 2>/dev/null || true; "
                "if [ -d ~/openclaw ]; then ln -sf ~/.openclaw_secrets/.env ~/openclaw/.env; fi; "
                "if [ -d ~/workspace/projects/openclaw ]; then ln -sf ~/.openclaw_secrets/.env ~/workspace/projects/openclaw/.env; fi; "
                "if [ -d ~/Documents/projects/openclaw ]; then ln -sf ~/.openclaw_secrets/.env ~/Documents/projects/openclaw/.env; fi"
            )
            subprocess.run(
                ["ssh", "-o", "ConnectTimeout=5", "-o", "BatchMode=yes", node, inject_cmd], 
                check=True, stderr=subprocess.DEVNULL, timeout=10
            )
            
        return f"✅ Node {node} securely fortified."
    except subprocess.TimeoutExpired:
        return f"❌ Node {node} Failed Fast: TimeoutExpired (Took > 10s)."
    except subprocess.CalledProcessError:
        return f"❌ Node {node} Failed Fast: BatchMode Auth Rejection or Connectivity."
    except Exception as e:
        return f"❌ Node {node} Failed Fast: {type(e).__name__}."

def sync():
    print("🚀 Initiating Vault-to-Env Secure Sync (Concurrent Fail-Fast Mode)...")
    if not os.path.exists(SECRETS_FILE):
        print(f"Error: Flattened secrets file {SECRETS_FILE} not found. Please run flatten_secrets.py first.")
        return

    with open(SECRETS_FILE, "r", encoding="utf-8") as f:
        secrets = json.load(f)

    env_content = "# OpenClaw Autogenerated Secure Env (Vault-to-Env Protocol)\n"
    for k, v in secrets.items():
        v_escaped = str(v).replace('"', '\\"')
        env_content += f'export {k}="{v_escaped}"\n'

    # 1. Write locally to Node 01
    with open(LOCAL_ENV, "w", encoding="utf-8") as f:
        f.write(env_content)
    os.chmod(LOCAL_ENV, 0o600)
    print(f"✅ Local {LOCAL_ENV} created/updated (chmod 600).")

    # 2. Inject into local Node 01 bash/zsh profiles
    for rc in [".zshrc", ".bash_profile", ".bashrc"]:
        rc_path = os.path.expanduser(f"~/{rc}")
        if os.path.exists(rc_path):
            with open(rc_path, "r") as f:
                content = f.read()
            if "source ~/.openclaw_env" not in content:
                with open(rc_path, "a") as f:
                    f.write("\n# OpenClaw Secure Secrets Envelope\n[ -f ~/.openclaw_env ] && source ~/.openclaw_env\n")

    print(f"\n⏳ Dispatching concurrent fleet synchronization to {NODES}...")
    # 3. Target remote nodes concurrently with Fail-Fast pool
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
        futures = {executor.submit(sync_node, node): node for node in NODES}
        for future in concurrent.futures.as_completed(futures):
            print("   " + future.result())

    print("\n🎉 Vault-to-Env deployment complete.")

if __name__ == "__main__":
    sync()
