#!/usr/bin/env python3
"""
ArXiv Fallback Protocol for Research Radar (Consumer-Side)

When Tavily API is exhausted and produces no usable data, this script
supplements the daily RAW.md with ArXiv search results for all configured
radar sectors.

Usage:
    python3 radar_arxiv_fallback.py --date 2026-03-25
"""
import os
import sys
import json
import subprocess
import argparse
from pathlib import Path

WORKSPACE_DIR = Path(os.path.expanduser("~/workspace"))
RAW_DATA_DIR = WORKSPACE_DIR / "docs" / "research_ideation" / "radar_raw_data"
TARGETS_PATH = WORKSPACE_DIR / "docs" / "research_ideation" / "radar_targets.json"
ARXIV_SCRIPT = Path(__file__).resolve().parent.parent.parent / "academic-search" / "scripts" / "search_arxiv.py"

SUPPLEMENT_MARKER = "# 📚 ArXiv Supplement"


def check_tavily_failure(raw_path: Path) -> float:
    """Returns the ratio of FATAL TAVILY errors in the RAW file."""
    with open(raw_path, "r") as f:
        content = f.read()
    
    total_sectors = content.count("### 🎯 Sector:") + content.count("### 🎓") + content.count("### 🏢") + content.count("### ✨")
    fatal_count = content.count("FATAL: ENGINE OFFLINE (TAVILY)")
    
    if total_sectors == 0:
        return 0.0
    return fatal_count / total_sectors


def search_arxiv(query: str, max_results: int = 10) -> str:
    """Call the academic-search ArXiv script and return raw JSON output."""
    try:
        result = subprocess.run(
            ["python3", str(ARXIV_SCRIPT), "search",
             "--query", query,
             "--max_results", str(max_results),
             "--sort_by", "date"],
            capture_output=True, text=True, timeout=30
        )
        return result.stdout.strip()
    except Exception as e:
        return json.dumps({"error": str(e)})


def run_fallback(date_str: str, force: bool = False):
    raw_path = RAW_DATA_DIR / f"{date_str}_RAW.md"
    
    if not raw_path.exists():
        print(f"❌ RAW file not found: {raw_path}")
        sys.exit(1)
    
    # Check if supplement already exists
    with open(raw_path, "r") as f:
        content = f.read()
    
    if SUPPLEMENT_MARKER in content and not force:
        print(f"⚠️ ArXiv Supplement already exists in {raw_path.name}. Use --force to overwrite.")
        return
    
    # Check Tavily failure rate
    failure_rate = check_tavily_failure(raw_path)
    print(f"📊 Tavily failure rate: {failure_rate:.0%}")
    
    if failure_rate < 0.5 and not force:
        print(f"✅ Tavily failure rate ({failure_rate:.0%}) below 50% threshold. No fallback needed.")
        return
    
    print(f"🚨 Tavily failure rate ({failure_rate:.0%}) exceeds threshold. Triggering ArXiv Fallback...")
    
    # Load targets
    with open(TARGETS_PATH, "r") as f:
        targets = json.load(f)
    
    sectors = targets.get("radar_sectors", {})
    supplement_lines = [f"\n\n{SUPPLEMENT_MARKER} for {date_str}\n"]
    supplement_lines.append(f"> Auto-generated by ArXiv Fallback Protocol (Tavily failure rate: {failure_rate:.0%})\n")
    
    for name, data in sectors.items():
        query = data["query"]
        tags = data.get("tags", [])
        
        print(f"  🔍 Searching ArXiv for [{name}]...")
        result = search_arxiv(query)
        
        supplement_lines.append(f"\n## 📦 Raw Sector: {name}")
        supplement_lines.append(f"**Tags**: {', '.join(tags)}")
        supplement_lines.append(f"### 📚 ArXiv (Academic Fallback)")
        supplement_lines.append(result)
        supplement_lines.append("\n---")
    
    # Append to RAW file
    with open(raw_path, "a") as f:
        f.write("\n".join(supplement_lines))
    
    print(f"✅ ArXiv Supplement appended to {raw_path.name} ({len(sectors)} sectors)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="ArXiv Fallback Protocol for Research Radar")
    parser.add_argument("--date", type=str, required=True, help="Date string (YYYY-MM-DD)")
    parser.add_argument("--force", action="store_true", help="Force re-supplement even if already exists or Tavily rate is low")
    args = parser.parse_args()
    
    run_fallback(args.date, args.force)
