#!/usr/bin/env python3
import os
import sys
import subprocess
import datetime
from pathlib import Path

RADAR_KEYWORDS = {
    "CaLaM": "Topological Data Analysis OR Topological Analysis",
    "Frenet": "SE(3) Equivariance OR Hamiltonian Neural Networks",
    "PESSO": "Spectral FlashAttention OR Neural Operator",
    "PhysDiff": "Energy-Conserving Quantization OR Physics-Informed",
    "RLPF": "Reinforcement Learning Fluid OR PDE RL Reward",
    "Composition": "Neural Operator Composition OR Zero-shot Multiphysics",
    "MultiAgent": "Multi-Agent Math Reasoning OR LLM Arbitrage"
}

WORKSPACE_DIR = Path(os.path.expanduser("~/workspace"))
REPORTS_DIR = WORKSPACE_DIR / "docs" / "research_ideation" / "radar_reports"
PDCA_FILE = WORKSPACE_DIR / "docs" / "projects_pdca" / "05_RESEARCH_RADAR_PDCA.md"

ACADEMIC_SEARCH_PATH = os.path.expanduser("~/Documents/projects/openclaw/skills/academic-search/scripts/search_arxiv.py")

# Context Files
PI_PROFILE_PATH = os.path.expanduser("~/Documents/projects/openclaw/skills/research-assistant/knowledge/profiles/pi_profile_xiaohua_liu.md")
IDEA_LIST_PATH = WORKSPACE_DIR / "docs" / "research_ideation" / "EXTENSION_IDEA_MASTER.md"

def read_file_safe(path):
    try:
        with open(path, "r") as f:
            return f.read()
    except Exception as e:
        return f"Error reading {path}: {e}"

def run_search(query: str, max_results: int = 5) -> str:
    try:
        result = subprocess.run(
            ["python3", ACADEMIC_SEARCH_PATH, "search", "--query", query, "--max_results", str(max_results)],
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout
    except subprocess.CalledProcessError as e:
        return f"*Error retrieving results for this query.*"
    except FileNotFoundError:
        return f"*Error: academic-search script not found.*"

import urllib.request
import urllib.error
import json

def call_gemini(prompt: str) -> str:
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        return "Error calling Gemini: GEMINI_API_KEY environment variable is not set."
    
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent?key={api_key}"
    headers = {'Content-Type': 'application/json'}
    data = json.dumps({
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"temperature": 0.2}
    }).encode('utf-8')
    
    try:
        req = urllib.request.Request(url, data=data, headers=headers)
        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode())
            return result['candidates'][0]['content']['parts'][0]['text']
    except Exception as e:
        return f"Error calling Gemini via REST API: {str(e)}"

def process_results_with_llm(category: str, raw_results: str) -> str:
    if "*Error" in raw_results or len(raw_results.strip()) < 50:
        return ""
        
    pi_profile = read_file_safe(PI_PROFILE_PATH)
    idea_list = read_file_safe(IDEA_LIST_PATH)
    
    prompt = f"""
You are the Cognitive Alignment Engine for Dr. Xiaohua Liu's Research Radar.
Your job is to read raw academic paper results from arXiv and cross-examine them against the PI's research profile, active projects, and idea lists.

### 1. PI Profile & Active P0 Projects:
{pi_profile}

### 2. Emerging Idea List (For threat/opportunity detection):
{idea_list}

### 3. Captured arXiv Papers for Category: {category}
{raw_results}

### Task:
You must strictly execute the PURE-T protocol (Trim/Filter).
Do NOT summarize every paper. Most papers are irrelevant.
Only report on MAX 2 papers if and ONLY if they directly:
- WARNING: Pose a threat (someone is publishing our Idea List).
- SOLUTION: Offer a direct methodological solution to our active P0 projects (CaLaM, Frenet, PESSO, PhysDiff).
- OPPORTUNITY: Strongly align as a foundation for his NSFC/Grants.

If no papers meet this high bar, output EXACTLY: "NO_HIGH_VALUE_TARGETS".
Otherwise, output a highly concise strategic brief in Markdown:
For each high-value paper:
- **Title**: ...
- **Classification**: [Threat WARNING] / [Method SOLUTION] / [Grant OPPORTUNITY]
- **Actionable Insight**: 1-2 sentences on exactly why this matters and what Dr. Liu should do.
"""
    return call_gemini(prompt)

def generate_report():
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    today_str = datetime.datetime.now().strftime("%Y-%m-%d")
    report_path = REPORTS_DIR / f"{today_str}_RADAR_V2_REPORT.md"
    
    print(f"📡 Initiating Cognitive Radar Sweep for {today_str}...")
    
    report_content = [
        f"# 📡 Radar V2 Cognitive Intel Report: {today_str}",
        "> **Auto-generated by Research-Radar V2 (Cognitive Engine)**\n",
        "## Strategic High-Value Targets\n"
    ]
    
    found_leads = []
    
    for category, query in RADAR_KEYWORDS.items():
        print(f"  -> Scanning & Analyzing sector: {category}")
        
        raw_results = run_search(query, max_results=5)
        
        if "*Error" not in raw_results:
            analysis = process_results_with_llm(category, raw_results)
            if analysis and "NO_HIGH_VALUE_TARGETS" not in analysis and "Error calling Gemini" not in analysis:
                report_content.append(f"### 🎯 Sector: {category}")
                report_content.append(analysis)
                report_content.append("\n---\n")
                found_leads.append(category)
            else:
                 print(f"     [Filtered] No targets met the cognitive threshold or LLM error.")

    if not found_leads:
        report_content.append("\n*No critical threats or high-value breakthroughs detected today.*")

    with open(report_path, "w") as f:
        f.write("\n".join(report_content))
    
    print(f"✅ Sweep complete. V2 Intel written to {report_path}")
    update_pdca(today_str, report_path, found_leads)

def update_pdca(date_str: str, report_path: Path, leads: list):
    if not PDCA_FILE.exists(): return
    leads_str = ", ".join(leads) if leads else "No major leads"
    new_row = f"| {date_str} (V2) | `../research_ideation/radar_reports/{report_path.name}` | {leads_str} | ✅ Cognitive Sweep OK |\n"
    
    with open(PDCA_FILE, "r") as f: content = f.read()
    if "| *待首次执行*" in content: content = content.replace("| *待首次执行* | - | - | ⏳ 等待扫掠 |", new_row.strip())
    else: content += new_row
    with open(PDCA_FILE, "w") as f: f.write(content)

import argparse

def git_sync_workspace():
    print("🔄 Synchronizing Radar V2 findings to Global Workspace (Git-as-SSoT)...")
    try:
        subprocess.run(["git", "add", "."], cwd=str(WORKSPACE_DIR), check=True)
        # Check if there's anything to commit
        status = subprocess.run(["git", "status", "--porcelain"], cwd=str(WORKSPACE_DIR), capture_output=True, text=True)
        if not status.stdout.strip():
            print("   [Skip] No new files to commit.")
            return
        subprocess.run(["git", "commit", "-m", "[Auto] Radar V2 Intel Sync"], cwd=str(WORKSPACE_DIR), check=True)
        subprocess.run(["git", "pull", "--rebase"], cwd=str(WORKSPACE_DIR), check=True)
        subprocess.run(["git", "push"], cwd=str(WORKSPACE_DIR), check=True)
        print("✅ Git Sync Complete. Results deposited to SSoT.")
    except subprocess.CalledProcessError as e:
        print(f"⚠️ Git Sync Warning: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Cognitive Radar V2 Daemon")
    parser.add_argument("--sectors", nargs="+", help="Specific sectors to scan (e.g., CaLaM Frenet)", default=[])
    args = parser.parse_args()
    
    # Filter keywords if sectors are provided
    if args.sectors:
        RADAR_KEYWORDS = {k: v for k, v in RADAR_KEYWORDS.items() if k in args.sectors}
        if not RADAR_KEYWORDS:
            print(f"❌ Error: Provided sectors {args.sectors} do not exist in the radar registry.")
            sys.exit(1)
            
    generate_report()
    git_sync_workspace()
