#!/usr/bin/env python3

import argparse
import sys
import json
import wandb
import os
import subprocess
from dotenv import load_dotenv

load_dotenv()

def get_api_key():
    key = os.getenv("WANDB_API_KEY")
    if not key:
        print(json.dumps({"error": "WANDB_API_KEY not found in environment"}))
        sys.exit(1)
    return key

def log_metric(args):
    try:
        wandb.login(key=get_api_key())
        
        project = args.project
        metric_name = args.metric
        value = args.value
        
        # Resume or start run
        run = wandb.init(project=project, resume="allow")
        
        wandb.log({metric_name: value})
        
        result = {
            "status": "success",
            "project": project,
            "run_id": run.id,
            "run_name": run.name,
            "metric": metric_name,
            "value": value
        }
        print(json.dumps(result))
        
        run.finish()
        
    except Exception as e:
        print(json.dumps({"error": str(e)}))
        sys.exit(1)

def list_runs(args):
    try:
        api = wandb.Api(api_key=get_api_key())
        
        path = args.path # entity/project
        if "/" not in path:
            # Assume default entity if not provided? Or just project name
            # api.runs(path) might work if user is default
            pass
            
        print(f"Fetching runs for {path}...", file=sys.stderr)
        runs = api.runs(path)
        
        run_list = []
        for run in runs:
            run_list.append({
                "id": run.id,
                "name": run.name,
                "state": run.state,
                "url": run.url
            })
            if len(run_list) >= args.limit:
                break
                
        print(json.dumps(run_list))
        
    except Exception as e:
        print(json.dumps({"error": str(e)}))
        sys.exit(1)

def export_latex(args):
    """Read a W&B Run Summary and write LaTeX \\newcommand macros.
    
    Usage:
        wandb_tool.py export_latex \\
            --run  darren_qing/calam/runs/mcohwyrw \\
            --keys j_score_pct avg_toxicity n_evaluated \\
            --out  paper/macros/results.tex
    
    Output (appended or created):
        \\newcommand{\\jScorePct}{91.3\\%}
        \\newcommand{\\avgToxicity}{0.12}
        ...
    """
    try:
        api = wandb.Api(api_key=get_api_key())
        run = api.run(args.run)          # accepts entity/project/runs/RUN_ID
        summary = run.summary._json_dict

        # ── helper: metric key → LaTeX command name ──────────────────────
        def to_cmd(key: str) -> str:
            """j_score_pct  →  \\jScorePct  (camelCase, no underscore)"""
            parts = key.split("_")
            return "".join(p.capitalize() for p in parts)

        # ── helper: format value ──────────────────────────────────────────
        def fmt(val) -> str:
            if isinstance(val, float):
                # percentages stored as 0-100 kept as-is; 0-1 fractions * 100
                if args.pct_keys and key in args.pct_keys:
                    return f"{val:.1f}\\%"
                return f"{val:.4f}"
            return str(val)

        lines = [
            f"% Auto-generated by wandb_tool.py export_latex",
            f"% Source: https://wandb.ai/{args.run}",
            f"% Generated: $(date)",
            "",
        ]

        requested_keys = args.keys if args.keys else list(summary.keys())
        missing = []
        for key in requested_keys:
            if key not in summary:
                missing.append(key)
                continue
            val = summary[key]
            cmd_name = to_cmd(key)
            val_str = fmt(val)
            lines.append(f"\\newcommand{{\\{cmd_name}}}{{{val_str}}}")

        output = "\n".join(lines) + "\n"

        if args.out:
            import pathlib
            out_path = pathlib.Path(args.out)
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_text(output)
            result = {"status": "success", "file": str(out_path),
                      "keys_written": [k for k in requested_keys if k not in missing],
                      "keys_missing": missing,
                      "run_url": run.url}
        else:
            print(output)
            result = {"status": "success", "keys_missing": missing, "run_url": run.url}

        if missing:
            result["warning"] = f"Keys not found in W&B Summary: {missing}"

        print(json.dumps(result), file=sys.stderr)

    except Exception as e:
        print(json.dumps({"error": str(e)}))
        sys.exit(1)

def probe_env(args):
    target_hosts = [args.remote] if args.remote else ["localhost"]
    api_key = get_api_key()
    
    # We want to search standard conda environment roots, plus the jhdx array
    search_dirs = ["~/.conda/envs", "/opt/conda/envs", "/jhdx0003008/envs", "/home/kaixin/.conda/envs"]
    
    # The deep probe: Verify the binary, the package, the network, and the API key validity.
    probe_script = f"""
    export WANDB_API_KEY='{api_key}'
    DIRS="{" ".join(search_dirs)}"
    for d in $DIRS; do
      eval d=$d
      if [ -d "$d" ]; then
        for env in "$d"/*; do
          if [ -x "$env/bin/python" ]; then
            if "$env/bin/python" -c "import wandb, os; api=wandb.Api(api_key=os.environ.get('WANDB_API_KEY')); api.default_entity" >/dev/null 2>&1; then
              echo "$env/bin/python"
            fi
          fi
        done
      fi
    done
    """
    
    results = {}
    for host in target_hosts:
        try:
            if host in ["localhost", "127.0.0.1"]:
                cmd = ["/bin/bash", "-c", probe_script]
            else:
                cmd = ["ssh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=10", host, probe_script]
            
            res = subprocess.run(cmd, capture_output=True, text=True)
            if res.returncode == 0:
                valid_paths = [p for p in res.stdout.strip().split("\n") if p]
                results[host] = valid_paths
            else:
                results[host] = {"error": res.stderr.strip() or f"Command failed with exit {res.returncode}"}
        except Exception as e:
            results[host] = {"error": str(e)}
            
    print(json.dumps({"status": "success", "probe_results": results}, indent=2))


def main():
    parser = argparse.ArgumentParser(description="WandB Skill Tool")
    subparsers = parser.add_subparsers(dest="command")
    
    # log
    l_parser = subparsers.add_parser("log")
    l_parser.add_argument("--project", required=True, help="WandB Project Name")
    l_parser.add_argument("--metric", required=True, help="Metric Name")
    l_parser.add_argument("--value", type=float, required=True, help="Metric Value")
    
    # runs
    r_parser = subparsers.add_parser("runs")
    r_parser.add_argument("--path", required=True, help="Project path (entity/project)")
    r_parser.add_argument("--limit", type=int, default=10, help="Limit number of runs")

    # export_latex
    el_parser = subparsers.add_parser(
        "export_latex",
        help="Export W&B Run Summary metrics as LaTeX \\newcommand macros"
    )
    el_parser.add_argument(
        "--run", required=True,
        help="Full run path: entity/project/runs/RUN_ID"
    )
    el_parser.add_argument(
        "--keys", nargs="*", default=None,
        help="Metric keys to export (default: all summary keys)"
    )
    el_parser.add_argument(
        "--pct_keys", nargs="*", default=None,
        help="Keys to format as percentages with \\%% suffix"
    )
    el_parser.add_argument(
        "--out", default=None,
        help="Output .tex file path (stdout if omitted)"
    )
    
    # probe
    p_parser = subparsers.add_parser(
        "probe",
        help="Probe Conda environments for W&B readiness across distributed nodes"
    )
    p_parser.add_argument(
        "--remote", default=None,
        help="Specific remote host to probe via SSH (e.g., 90-1, gpu)"
    )
    
    args = parser.parse_args()
    
    if args.command == "log":
        log_metric(args)
    elif args.command == "runs":
        list_runs(args)
    elif args.command == "export_latex":
        export_latex(args)
    elif args.command == "probe":
        probe_env(args)
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
