#!/usr/bin/env python3
import os
import re

def generate_index():
    """
    Scans the OpenClaw skills directory and generates a markdown index
    of all available skills and their descriptions.
    """
    home_dir = os.path.expanduser("~")
    skills_dir = os.path.join(home_dir, "Documents", "projects", "openclaw", "skills")
    index_file = os.path.join(skills_dir, "OPENCLAW_SKILLS_INDEX.md")
    
    if not os.path.exists(skills_dir):
        print(f"❌ ERROR: Skills directory {skills_dir} not found.")
        return

    skills = []
    
    for item in sorted(os.listdir(skills_dir)):
        item_path = os.path.join(skills_dir, item)
        if os.path.isdir(item_path):
            skill_md_path = os.path.join(item_path, "SKILL.md")
            if os.path.exists(skill_md_path):
                # Extract description from frontmatter or first paragraph
                description = "No description provided."
                try:
                    with open(skill_md_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                        
                        # Try to find description in YAML frontmatter
                        yaml_match = re.search(r'description:\s*([^\n]+)', content)
                        if yaml_match:
                            description = yaml_match.group(1).strip()
                        else:
                            # Fallback: look for the first non-header, non-empty line
                            lines = [line.strip() for line in content.split('\n') if line.strip() and not line.startswith('#') and not line.startswith('---')]
                            if lines:
                                description = lines[0][:100] + "..." if len(lines[0]) > 100 else lines[0]
                except Exception as e:
                    description = f"(Error reading description: {e})"
                
                skills.append({
                    "name": item,
                    "path": item_path,
                    "description": description
                })

    # Write the index file
    try:
        with open(index_file, 'w', encoding='utf-8') as f:
            f.write("# 🛠️ OpenClaw Skills Index (Auto-Generated)\n\n")
            f.write("> **System Notice**: This file is automatically generated whenever the Agent context is restored. It serves as the definitive menu for all available Agent capabilities.\n\n")
            f.write("## Available Skills\n\n")
            
            for skill in skills:
                f.write(f"### `{skill['name']}`\n")
                f.write(f"- **Description**: {skill['description']}\n")
                f.write(f"- **Path**: `{skill['path']}`\n")
                f.write(f"- **Instruction File**: `view_file {os.path.join(skill['path'], 'SKILL.md')}`\n\n")
                
        print(f"✅ SKILL_INDEX_UPDATED: Successfully cataloged {len(skills)} skills into {index_file}")
    except Exception as e:
        print(f"❌ ERROR: Failed to write index file: {e}")

if __name__ == "__main__":
    generate_index()
