import sys
import os
import subprocess
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor

def render_tmp_graphviz(dot_code):
    """Render DOT code to a temporary PNG file."""
    tmp_dot = "/tmp/ppt_tmp_graph.dot"
    tmp_png = "/tmp/ppt_tmp_graph.png"
    with open(tmp_dot, "w") as f:
        f.write(dot_code)
    try:
        subprocess.run(["dot", "-Tpng", tmp_dot, f"-o{tmp_png}"], check=True, capture_output=True)
        return tmp_png
    except Exception as e:
        print(f"Graphviz rendering failed: {e}", file=sys.stderr)
        return None

def render_tmp_banana(prompt):
    """Render artistic image using Nano Banana Pro script"""
    tmp_png = "/tmp/ppt_tmp_banana.png"
    # Ensure uv is in path or run the script via sys.executable if it's identical
    # The Banana skill uses `uv run scripts/generate_image.py`
    banana_script_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../nano-banana-pro/scripts/generate_image.py"))
    
    try:
        subprocess.run(["uv", "run", banana_script_path, "--prompt", prompt, "--filename", tmp_png, "--resolution", "1K"], check=True, capture_output=True)
        return tmp_png
    except Exception as e:
        print(f"Banana Pro rendering failed: {e}", file=sys.stderr)
        return None

def create_ppt(title, content_pages, output_path):
    prs = Presentation()
    primary_color = RGBColor(0, 51, 102)

    # Title Slide
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by OpenClaw Academic Assistant"

    # Content Slides
    for page in content_pages:
        has_dot = bool(page.get('image_dot'))
        has_banana = bool(page.get('image_prompt'))
        has_image = has_dot or has_banana
        
        # Use a blank layout if there's an image, else use standard bullet layout
        layout = prs.slide_layouts[5] if has_image else prs.slide_layouts[1]
        slide = prs.slides.add_slide(layout)
        
        # Set Slide Title
        title_shape = slide.shapes.title
        title_shape.text = page.get('title', 'Content')
        title_shape.text_frame.paragraphs[0].font.color.rgb = primary_color
        
        bullets = page.get('bullets', [])
        
        if has_image:
            # Layout: Text on Left, Image on Right
            # Add text box
            txBox = slide.shapes.add_textbox(Inches(0.5), Inches(1.5), Inches(4.5), Inches(5.5))
            tf = txBox.text_frame
            for i, bullet in enumerate(bullets):
                p = tf.add_paragraph()
                p.text = str(bullet)
                p.level = 0
                p.font.size = Pt(20)
                p.space_after = Pt(10)
            
            # Render and insert image
            img_path = None
            if has_dot:
                img_path = render_tmp_graphviz(page['image_dot'])
            elif has_banana:
                img_path = render_tmp_banana(page['image_prompt'])
                
            if img_path and os.path.exists(img_path):
                slide.shapes.add_picture(img_path, Inches(5.2), Inches(1.5), width=Inches(4.5))
        else:
            # Layout: Standard Bullets
            tf = slide.shapes.placeholders[1].text_frame
            tf.clear()
            for i, bullet in enumerate(bullets):
                p = tf.add_paragraph()
                p.text = str(bullet)
                p.level = 0
                p.font.size = Pt(24)
                p.space_after = Pt(14)
                if i == 0: p.font.bold = True

    prs.save(output_path)
    print(f"PPT successfully created and saved to: {output_path}")

if __name__ == "__main__":
    import json
    import argparse
    
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", required=False, help="JSON string representing the presentation structure")
    parser.add_argument("--input", required=False, help="Absolute path to JSON file representing the presentation structure")
    parser.add_argument("--output", required=True, help="Absolute path to save the .pptx file")
    
    args = parser.parse_args()
    
    try:
        if args.input:
            with open(args.input, 'r', encoding='utf-8') as f:
                data = json.load(f)
        elif args.data:
            data = json.loads(args.data)
        else:
            raise ValueError("Must provide either --data or --input")
            
        create_ppt(data.get("title", ""), data.get("pages", []), args.output)
    except Exception as e:
        print(f"Error generating PPT: {e}", file=sys.stderr)
        sys.exit(1)
