name: Sync upstream

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *' # Run at midnight every day
  workflow_dispatch: # Enable manual trigger from GitHub UI

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo

    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0 # fetch all history for all branches and tags

    # Step 2: run the sync action
    - name: Sync upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: main
        # Define the upstream repo
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_repo: openclaw/openclaw
        upstream_sync_branch: main
        
        test_mode: false
      
    # Step 3: Print a message based on the result
    - name: Check sync result
      if: steps.sync.outputs.has_new_commits == 'true'
      run: echo "New commits were found and synced."
      
    - name: Check sync result (No new commits)
      if: steps.sync.outputs.has_new_commits == 'false'
      run: echo "No new commits found. Sync not needed."
